### ISSUE TITLE
Noisy warnings from tahu::signature during unit testing

### ISSUE THREAD

**Issue by seanmil** [hlindberg/tahu#5]
I decided to try out `tahu::signature` for a rewrite I'm working on and it is working great so far in testing (thank you!) except that when I'm running unit tests I get a set of warning messages spewed for each test which ends up invoking a code path that calls `tahu::signature`:

```
spec/fixtures/modules/tahu/lib/puppet/functions/tahu/signature.rb:222: warning: already initialized constant Puppet::Pops::Loader::RubyFunctionInstantiator::NAME
spec/fixtures/modules/tahu/lib/puppet/functions/tahu/signature.rb:222: warning: previous definition of NAME was here
spec/fixtures/modules/tahu/lib/puppet/functions/tahu/signature.rb:223: warning: already initialized constant Puppet::Pops::Loader::RubyFunctionInstantiator::TYPE
spec/fixtures/modules/tahu/lib/puppet/functions/tahu/signature.rb:223: warning: previous definition of TYPE was here
spec/fixtures/modules/tahu/lib/puppet/functions/tahu/signature.rb:224: warning: already initialized constant Puppet::Pops::Loader::RubyFunctionInstantiator::OPT
spec/fixtures/modules/tahu/lib/puppet/functions/tahu/signature.rb:224: warning: previous definition of OPT was here
spec/fixtures/modules/tahu/lib/puppet/functions/tahu/signature.rb:225: warning: already initialized constant Puppet::Pops::Loader::RubyFunctionInstantiator::META
spec/fixtures/modules/tahu/lib/puppet/functions/tahu/signature.rb:225: warning: previous definition of META was here
spec/fixtures/modules/tahu/lib/puppet/functions/tahu/signature.rb:226: warning: already initialized constant Puppet::Pops::Loader::RubyFunctionInstantiator::REPEATING
spec/fixtures/modules/tahu/lib/puppet/functions/tahu/signature.rb:226: warning: previous definition of REPEATING was here
```

I see the lines of code in `tahu::signature` where the constants are defined, but it isn't clear to me what the best way to address this is.

Thanks!

**Comment by hlindberg** [comment]
yeah so that is not good - should not have done what I did there. The best is to replace all the references to those constants with the actual string (e.g. `'name'` instead of `NAME`) and instead turn on frozen string literals in Ruby - like described here: https://stackoverflow.com/questions/37799296/what-does-the-comment-frozen-string-literal-true-do. With the frozen string literals the effect is more or less the same and it is up to Ruby to optimizes (which it should from Ruby 2.3 onwards).

**Comment by hlindberg** [comment]
While those constants will not really change between versions, it is still kind of leaking between environments so would be a good thing to change. PR is very welcome should you have the time to make one.

**Comment by hlindberg** [comment]
I just pushed a new version that should fix this issue. @seanmil please reopen if it isn't working as expected.
